//存放常量的仓库
const SYNC_UPDATE = 'SYNC_UPDATE'
const REGISTER = 'REGISTER'
const LOGIN = 'LOGIN'
const STORAGE_USERNAME = 'STORAGE_USERNAME'
const LOGOUT = 'LOGOUT'
export {
  SYNC_UPDATE,
  REGISTER,
  LOGIN,
  STORAGE_USERNAME,
  LOGOUT
}
